package lang

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/eideroliveira/aspect/internal/spec"
)

// Swift targets a SwiftPM package. Each spec module becomes a library target
// under Sources/<Module>/ with tests under Tests/<Module>Tests/. The package
// declares both iOS and macOS platforms so `swift test` runs on the macOS
// host while the code stays deployable to iOS; UI code is expected to be
// SwiftUI, which compiles on both.
func init() {
	register(&Profile{
		Name:        "swift",
		DisplayName: "Swift",
		SourceExt:   ".swift",
		CodeDir:     func(m string) string { return "Sources/" + PascalCase(m) + "/" },
		TestDir:     func(m string) string { return "Tests/" + PascalCase(m) + "Tests/" },
		IsTestFile:  func(p string) bool { return strings.HasPrefix(p, "Tests/") },
		Init:        func(string, *spec.Spec, *spec.Tier) error { return nil },
		Sync:        swiftSync,
		Steps: func(module string) [][]string {
			return [][]string{
				{"swift", "build"},
				{"swift", "test", "--filter", PascalCase(module) + "Tests"},
			}
		},
		CoderRules: `Swift rules:
- The package manifest (Package.swift) is generated by the pipeline; never write it. A module named "stock" is the SwiftPM target Stock, and its files live under Sources/Stock/. Only write files there.
- Depend on other modules with "import <Module>" (PascalCase of the module name). Do not re-implement them.
- The package builds for both iOS and macOS so tests run on the host. Write SwiftUI for user interfaces and guard UIKit-only APIs with #if canImport(UIKit). Keep logic out of views so it is testable.
- Use only Foundation, Swift standard library, SwiftUI/Combine/Observation, and the packages listed under the stack section.
- Prefer value types, strict concurrency (Sendable, actors) and Swift 5.9+ features. Mark public API explicitly public.`,
		TesterRules: `Swift rules:
- Tests live under Tests/<Module>Tests/ as XCTest cases that "@testable import <Module>". Never write files under Sources/.
- XCTest only, no third-party assertion libraries.
- Concurrency constraints get async tests using TaskGroup; the pipeline runs on macOS with the default Swift toolchain.
- Property-style tests use a seeded RandomNumberGenerator so failures reproduce.`,
	})
}

// swiftSync regenerates Package.swift listing every module generated so far,
// in plan order, with inter-target dependencies from the spec and external
// packages from the stack section. Only targets whose directory exists are
// declared: with modules generated in parallel, a module whose tests are not
// written yet must not break another module's build.
func swiftSync(root string, s *spec.Spec, t *spec.Tier, modules []string) error {
	var present []string
	hasTests := map[string]bool{}
	for _, m := range modules {
		if _, err := os.Stat(filepath.Join(root, "Sources", PascalCase(m))); err != nil {
			continue
		}
		present = append(present, m)
		if _, err := os.Stat(filepath.Join(root, "Tests", PascalCase(m)+"Tests")); err == nil {
			hasTests[m] = true
		}
	}
	modules = present
	pkgName := PascalCase(s.System.Name)
	if t.Name != "" {
		pkgName = PascalCase(s.System.Name + "_" + t.Name)
	}
	var b strings.Builder
	b.WriteString("// swift-tools-version:5.9\n// Generated by Aspect from the spec. Do not edit; edit the spec.\nimport PackageDescription\n\n")
	fmt.Fprintf(&b, "let package = Package(\n    name: %q,\n    platforms: [.iOS(.v17), .macOS(.v14)],\n", pkgName)

	var targets []string
	for _, m := range modules {
		targets = append(targets, fmt.Sprintf("%q", PascalCase(m)))
	}
	fmt.Fprintf(&b, "    products: [\n        .library(name: %q, targets: [%s]),\n    ],\n", pkgName, strings.Join(targets, ", "))

	var deps, products []string
	if ls := t.LanguageStack(); ls != nil {
		for _, f := range ls.Frameworks {
			if f.Module == "" {
				continue
			}
			pkg := packageName(f.Module)
			if f.Version != "" {
				deps = append(deps, fmt.Sprintf("        .package(url: %q, from: %q),", f.Module, f.Version))
			} else {
				deps = append(deps, fmt.Sprintf("        .package(url: %q, branch: \"main\"),", f.Module))
			}
			products = append(products, fmt.Sprintf(".product(name: %q, package: %q)", f.Name, pkg))
		}
	}
	if len(deps) > 0 {
		fmt.Fprintf(&b, "    dependencies: [\n%s\n    ],\n", strings.Join(deps, "\n"))
	}

	b.WriteString("    targets: [\n")
	for _, m := range modules {
		mod := t.Module(m)
		var tdeps []string
		if mod != nil {
			for _, d := range mod.DependsOn {
				tdeps = append(tdeps, fmt.Sprintf("%q", PascalCase(d)))
			}
		}
		tdeps = append(tdeps, products...)
		name := PascalCase(m)
		fmt.Fprintf(&b, "        .target(name: %q, dependencies: [%s]),\n", name, strings.Join(tdeps, ", "))
		if hasTests[m] {
			fmt.Fprintf(&b, "        .testTarget(name: %q, dependencies: [%q]),\n", name+"Tests", name)
		}
	}
	b.WriteString("    ]\n)\n")
	return os.WriteFile(filepath.Join(root, "Package.swift"), []byte(b.String()), 0o644)
}

// packageName derives the SwiftPM package identity from a repository URL:
// https://github.com/pointfreeco/swift-composable-architecture.git ->
// swift-composable-architecture.
func packageName(url string) string {
	name := url[strings.LastIndex(url, "/")+1:]
	return strings.TrimSuffix(name, ".git")
}
